"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class boolean_stamped_t(object):
    __slots__ = ["value", "time_stamp"]

    __typenames__ = ["boolean", "double"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.value = False
        self.time_stamp = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(boolean_stamped_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">bd", self.value, self.time_stamp))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != boolean_stamped_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return boolean_stamped_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = boolean_stamped_t()
        self.value = bool(struct.unpack('b', buf.read(1))[0])
        self.time_stamp = struct.unpack(">d", buf.read(8))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if boolean_stamped_t in parents: return 0
        tmphash = (0x9d9efd1128371b66) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if boolean_stamped_t._packed_fingerprint is None:
            boolean_stamped_t._packed_fingerprint = struct.pack(">Q", boolean_stamped_t._get_hash_recursive([]))
        return boolean_stamped_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", boolean_stamped_t._get_packed_fingerprint())[0]

