"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct


class formation_synth_t(object):
    __slots__ = ["seq_number", "length", "positions", "cost", "id_sender"]

    __typenames__ = ["int64_t", "int32_t", "double", "double", "int32_t"]

    __dimensions__ = [None, None, ["length"], None, None]

    def __init__(self):
        self.seq_number = 0
        self.length = 0
        self.positions = []
        self.cost = 0.0
        self.id_sender = 0

    def encode(self):
        buf = BytesIO()
        buf.write(formation_synth_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.seq_number, self.length))
        buf.write(struct.pack(">%dd" % self.length, *self.positions[: self.length]))
        buf.write(struct.pack(">di", self.cost, self.id_sender))

    def decode(data):
        if hasattr(data, "read"):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != formation_synth_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return formation_synth_t._decode_one(buf)

    decode = staticmethod(decode)

    def _decode_one(buf):
        self = formation_synth_t()
        self.seq_number, self.length = struct.unpack(">qi", buf.read(12))
        self.positions = struct.unpack(">%dd" % self.length, buf.read(self.length * 8))
        self.cost, self.id_sender = struct.unpack(">di", buf.read(12))
        return self

    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if formation_synth_t in parents:
            return 0
        tmphash = (0x9E6777A821F6BDE0) & 0xFFFFFFFFFFFFFFFF
        tmphash = (((tmphash << 1) & 0xFFFFFFFFFFFFFFFF) + (tmphash >> 63)) & 0xFFFFFFFFFFFFFFFF
        return tmphash

    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if formation_synth_t._packed_fingerprint is None:
            formation_synth_t._packed_fingerprint = struct.pack(">Q", formation_synth_t._get_hash_recursive([]))
        return formation_synth_t._packed_fingerprint

    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", formation_synth_t._get_packed_fingerprint())[0]
